### ISSUE TITLE
Push changes accumulated in master out to a new npm release

### ISSUE THREAD

**Issue by thesephist** [hackclub/design-system#15]
There have been lots of changes to HDS that our other projects don't have access to because we haven't released to NPM in a while. The more recent changes at the tip of master also seem to be breaking changes. We should make a release and investigate what those breaking changes are.

See also corresponding PR on hackclub/hackathons: https://github.com/hackclub/hackathons/pull/53

**Comment by lachlanjc** [comment]
Released: https://github.com/hackclub/design-system/releases/tag/0.0.1-17
